In [1]:
import pandas as pd
from tqdm import tqdm
import os

import sqlalchemy as sa
from sqlalchemy import Table, MetaData, Column, Integer, text

### Connect to the DB

Get the data related to the location tables

In [4]:
## You must have this driver installed on your local machine

username = os.getenv('AZURE_MSDS432_USERNAME')
password = os.getenv('AZURE_MSDS432_PASSWORD')
host = 'mysqlserver-432.database.windows.net'
database = 'mySampleDatabase'
authentication = "SqlPassword"
conn_string = sa.engine.url.URL(
     "mssql+pyodbc",
     username=username,
     password=password,
     host=host,
     port=1433,
     database=database,
     query={"driver": "ODBC Driver 18 for SQL Server", "authentication": authentication}
 )

engine = sa.create_engine(conn_string, pool_timeout=60)
connection = engine.connect()

In [9]:
get_evictions = """
SELECT *
FROM SF_Eviction_Notices_Raw;
"""

get_buyout_agreements = """
SELECT *
FROM SF_Buyout_Agreements_Raw;
"""

evictions = pd.read_sql_query(get_evictions, connection)
buyouts = pd.read_sql_query(get_buyout_agreements, connection)

In [8]:
evictions.head()

,id,eviction_id,address,city,state,zip,file_date,non_payment,breach,nuisance,...,other_cause,late_payments,lead_remediation,development,good_samaritan_ends,supervisor_district,neighborhood,shape,constraints_date,client_location
0,0,M220284,2000 Block Of Broadway Street,San Francisco,CA,94123,2022-02-18T00:00:00.000,False,True,False,...,False,False,False,False,False,2,Pacific Heights,"{'type': 'Point', 'coordinates': [-122.430824,...",nan,nan
1,1,M220262,500 Block Of Beale Street,San Francisco,CA,94105,2022-02-14T00:00:00.000,False,True,False,...,False,False,False,False,False,6,Financial District/South Beach,"{'type': 'Point', 'coordinates': [-122.38909, ...",nan,nan
2,2,M220049,2000 Block Of Broadway Street,San Francisco,CA,94123,2022-01-07T00:00:00.000,False,True,False,...,False,False,False,False,False,2,Pacific Heights,"{'type': 'Point', 'coordinates': [-122.430824,...",nan,nan
3,3,M211708,100 Block Of Bartlett Street,San Francisco,CA,94115,2021-11-12T00:00:00.000,False,False,True,...,False,False,False,False,False,9,Mission,"{'type': 'Point', 'coordinates': [-122.41979, ...",nan,nan
4,4,M211587,700 Block Of Fillmore Street,San Francisco,CA,94134,2021-10-25T00:00:00.000,False,False,True,...,False,False,False,False,False,5,Hayes Valley,"{'type': 'Point', 'coordinates': [-122.431305,...",nan,nan

In [10]:
buyouts.head()

,id,case_number,pre_buyout_disclosure_declaration_date,buyout_agreement_date,buyout_amount,number_of_tenants,address,zip_code,supervisor_district,analysis_neighborhood,point,geocoding_confidence,unknown_amount,other_consideration
0,0,B153174,2015-11-16T00:00:00.000,2016-03-28T00:00:00.000,55000,2,6439 (aka 6443) California Street,nan,nan,nan,nan,nan,nan,nan
1,1,B171997,2017-08-04T00:00:00.000,nan,nan,nan,676 10th Avenue,94118,1,Inner Richmond,"{'type': 'Point', 'coordinates': [-122.4681713...",100,nan,nan
2,2,B153129,2015-11-12T00:00:00.000,2016-02-19T00:00:00.000,35000,1,733 Fillmore Street,94117,5,Hayes Valley,"{'type': 'Point', 'coordinates': [-122.4313123...",100,nan,nan
3,3,B161104,2016-03-21T00:00:00.000,nan,nan,nan,877 Shotwell Street,94110,9,Mission,"{'type': 'Point', 'coordinates': [-122.4153385...",100,nan,nan
4,4,B172057,2017-08-09T00:00:00.000,2018-08-24T00:00:00.000,15000,1,759 06th Avenue,94118,1,Inner Richmond,"{'type': 'Point', 'coordinates': [-122.4638491...",100,nan,nan